version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"  # Update this to wherever your `package.json` is located
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"